name: Code Quality Checks

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run checks on'
        required: true

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 mypy bandit

    - name: Run Pylint
      run: |
        pylint geoframe || true
          
    - name: Run Flake8
      run: |
        flake8 geoframe || true

    - name: Run MyPy
      run: |
        mypy geoframe || true

    - name: Run Bandit
      run: |
        bandit -r geoframe || true